apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ms-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /hello-ms
        pathType: Prefix
        backend:
          service:
            name: hello-ms-service
            port:
              number: 8081
