apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-deployment
  labels:
    app: hello-ms 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-ms
  template:
    metadata:
      labels:
        app: hello-ms
    spec:
      containers:
      - name: hello-ms
        image: hafizjamil/ms:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.25"
            memory: "64Mi"
        env:
        - name: NODE_ENV
          value: "production"
