name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ms:latest

    - name: Set Git user
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"


    - name: Update image tag in deployment.yaml
      run: |
        git checkout main
        sed -i 's|hafizjamil/ms:[^ ]*|hafizjamil/ms:latest|g' manifest/deployment.yaml
        git add manifest/deployment.yaml
        git commit -m "Update image tag to latest"
        git push https://${{secrets.PAT}}@github.com/hafizj98/hello-ms.git main
