name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password-stdin: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: hafizjamil/ms:${{ github.sha }}

      - name: Update values.yaml
        run: |
          echo "image:" > ./ms-app/values.yaml
          echo "  repository: hafizjamil/ms" >> ./ms-app/values.yaml
          echo "  tag: ${{ github.sha }}" >> ./ms-app/values.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./ms-app/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin HEAD:main

      - name: Set image ID output
        run: echo "IMAGE_ID=${{ steps.docker_build.outputs.image-id }}" >> $GITHUB_ENV
